### ISSUE TITLE
libcontainer driver: consider `devices.DefaultSimpleDevices` and `devices.DefaultAllowedDevices`

### ISSUE THREAD

**Issue by fabiokung** [heroku/hsup#12]
Suggested by @dpiddy [here](https://github.com/heroku/hsup/pull/11#discussion_r23557014) and [here](https://github.com/heroku/hsup/pull/11#discussion_r23557045).

**Comment by fabiokung** [comment]
Fixed in @0e5733be667c8d66e

**Comment by dpiddy** [comment]
:+1:
